/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import fungsi.CRUD_MenuAnakKos;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BintangDiLangit
 */
public class vw_MenuAnakKos extends javax.swing.JFrame {

    /**
     * Creates new form vw_MenuAnakKos
     */
    private DefaultTableModel tabmode; // set model dari Jtable
    private ResultSet hasil; // tampil data
    CRUD_MenuAnakKos app = new  CRUD_MenuAnakKos();

    public vw_MenuAnakKos() {
        initComponents();
        tampil_database();
        this.setLocationRelativeTo(null);

    }

    public void tampil_database() {
        Object[] baris = {"Hari", "Nama Menu", "Jumlah Kalori"};
        tabmode = new DefaultTableModel(null, baris);
        jTable1.setModel(tabmode);
        try {
            hasil = app.tampilData();
            while (hasil.next()) {
                app.setJadwalHariMenuCatering(hasil.getString("hari"));
                app.setNamaMenuCatering(hasil.getString("nama"));
                app.setJumlahKaloriMenuCatering(hasil.getString("jumlahKalori"));

                String[] data = {app.getJadwalHariMenuCatering(), app.getNamaMenuCatering(), app.getJumlahKaloriMenuCatering()};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        insert = new javax.swing.JButton();
        hari = new javax.swing.JTextField();
        namaMenu = new javax.swing.JTextField();
        jumlahKalori = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        edit = new javax.swing.JButton();
        id = new javax.swing.JLabel();
        delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        insert.setText("Insert");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Hari");

        jLabel2.setText("Nama Menu");

        jLabel3.setText("Jumlah Kalori");

        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        delete.setText("delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hari, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumlahKalori, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(edit)
                                .addGap(53, 53, 53)
                                .addComponent(delete))
                            .addComponent(insert))))
                .addContainerGap(174, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insert)
                    .addComponent(jLabel2))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jumlahKalori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(edit)
                    .addComponent(delete))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
//                if (hari.getText().trim().equals("") && namaMenu.getText().trim().equals("") && jumlahKalori.getText().trim().equals("")) {
//            JOptionPane.showMessageDialog(null, "Maaf, Semua Field Masih Belum Diisi !");
//            hari.requestFocus();
//            namaMenu.requestFocus();
//            jumlahKalori.requestFocus();
//        } else if (hari.getText().trim().equals("")) {
//            JOptionPane.showMessageDialog(null, "Maaf, Hari belum diisi !");
//            hari.requestFocus();
//        } else if (namaMenu.getText().trim().equals("")) {
//            JOptionPane.showMessageDialog(null, "Maaf, Nama Menu belum diisi !");
//            namaMenu.requestFocus();
//        } else if (jumlahKalori.getText().trim().equals("")) {
//            JOptionPane.showMessageDialog(null, "Maaf, Harga Menu belum diisi !");
//            jumlahKalori.requestFocus();
//        } else {
        try {
            app.setJadwalHariMenuCatering(hari.getText());
            app.setNamaMenuCatering(namaMenu.getText());
            app.setJumlahKaloriMenuCatering(jumlahKalori.getText());

            app.simpanData(app.getJadwalHariMenuCatering(), app.getNamaMenuCatering(), app.getJumlahKaloriMenuCatering()
            );

            JOptionPane.showMessageDialog(null, "Data berhasil tersimpan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
//                tampil_database();
//                ResetText();
            tampil_database();
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "DATA SUDAH ADA");
        }
//        }
    }//GEN-LAST:event_insertActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        try {
                app.setJadwalHariMenuCatering(hari.getText());
                app.setNamaMenuCatering(namaMenu.getText());
                app.setJumlahKaloriMenuCatering(jumlahKalori.getText());

                app.ubahData(
                        app.getJadwalHariMenuCatering(),
                        app.getNamaMenuCatering(),
                        app.getJumlahKaloriMenuCatering()
                );

                JOptionPane.showMessageDialog(null, "Data berhasil diupdate", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                tampil_database();
//                ResetText();
            } catch (Exception e) {
                System.out.println(e);
                JOptionPane.showMessageDialog(null, "DATA SUDAH ADA");
            }
    }//GEN-LAST:event_editActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
         try {
            int row = jTable1.rowAtPoint(evt.getPoint());
            String hari_tabel = jTable1.getValueAt(row, 0).toString();
            String nama_menu = jTable1.getValueAt(row, 1).toString();
            String jumlahKalori_tabel = jTable1.getValueAt(row, 2).toString();

            hari.setText(hari_tabel);
            namaMenu.setText(nama_menu);
            jumlahKalori.setText(jumlahKalori_tabel);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        try {
            app.setJadwalHariMenuCatering(hari.getText());
            app.hapusData(app.getJadwalHariMenuCatering());
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            tampil_database();
//            ResetText();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data gagal dihapus", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }  
    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vw_MenuAnakKos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vw_MenuAnakKos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vw_MenuAnakKos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vw_MenuAnakKos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vw_MenuAnakKos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JTextField hari;
    private javax.swing.JLabel id;
    private javax.swing.JButton insert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jumlahKalori;
    private javax.swing.JTextField namaMenu;
    // End of variables declaration//GEN-END:variables
}
